### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by fulldecent** [myg0v/Simple-Bootstrap-Stripe-Payment-Form#13]
Please include a live example or at least screenshot so I can see what I am getting into before investing time with this project (and deciding to use Stripe).

**Comment by driton** [comment]
<img width="850" alt="not" src="https://cloud.githubusercontent.com/assets/634084/19692527/8ed55fcc-9ad8-11e6-9c0f-4f393844e83c.png">


Stripe form is not appearing in online mode ,even that I installed ssl certificate :(
Please help!

**Comment by fulldecent** [comment]
To be clear, are you still accepting contributions to this project?? If so would a PR that fixes this be in scope to be merged?
