### ISSUE TITLE
"Error! Invalid API Key Provided"

### ISSUE THREAD

**Issue by SteveLongoria** [myg0v/Simple-Bootstrap-Stripe-Payment-Form#14]
I've triple checked my secret and publishable keys yet I still get this error. See screenshot attached.

![screenshot 2016-09-18 at 2 26 18 pm](https://cloud.githubusercontent.com/assets/17738181/18619243/71d25cc0-7dac-11e6-8ab8-0784e7cb46b8.png)

**Comment by SteveLongoria** [comment]
Never mind, it was just an oversight on my part. :-/

**Comment by jrkelley32** [comment]
What was the oversight?  I've encountered the same problem.

Thanks!

**Comment by jrkelley32** [comment]
Got it.  Could be better documented that you need to remove the "<>"'s
