### ISSUE TITLE
TLS 1.0 Not Supported anymore

### ISSUE THREAD

**Issue by ghost** [myg0v/Simple-Bootstrap-Stripe-Payment-Form#17]
Hi, I have tried this payment form and I have received an error:

> _Error! Stripe no longer supports API requests made with TLS 1.0. Please initiate HTTPS connections with TLS 1.2 or later. You can learn more about this at https://stripe.com/blog/upgrading-tls._

How to overcome it ?

**Comment by TakesTheBiscuit** [comment]
This is an issue with your server

**Comment by EasyRenter** [comment]
Hello Manik,

I have the same issue. Did you find a solution to solve it ?

**Comment by manik-sidana** [comment]
I am not sure, but I had created my own form by then and the source code is with the client now.

**Comment by EasyRenter** [comment]
I understand. I was just testing different module for a better understanding of Stripe. Nevertheless, at last, i will need to make my own module :/ Thx for the reply !

**Comment by TakesTheBiscuit** [comment]
@EasyRenter Check out Stripe elements - it's pretty good!, i didn't even know of it's existence until recently

Demo:
https://stripe.github.io/elements-examples/

Source:
https://github.com/stripe/elements-examples/#example-1

**Comment by EasyRenter** [comment]
Thx @TakesTheBiscuit  for this sharing. I will check that right away.
For our problem, "TLS 1.0 Not Supported anymore", my solution was to update MAMP to V4. It seem that there were no other solution :)

**Comment by TakesTheBiscuit** [comment]
@EasyRenter Yes i did suspect your server needed TLS upgraded as there was some pretty major security holes in TLS 1.0; https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/

The new stripe elements lib is cracking; gets you up and running in 10 mins client side 

@myg0v this issue can safely be closed
